### ISSUE TITLE
Encountered Undefined offset

### ISSUE THREAD

**Issue by lf2eddie** [mark2me/wp-ga-count#1]
Hi,

Thanks for the creating such a great plug-in 
I followed the tutorial on this website "http://www.arno.tw/how-to-show-traffic-from-ga-to-wordpress/"
but I encounter an issue like the following message appear on my website.

Notice: Undefined offset: 7 in /home1/xxxxxxx/public_html/wp-content/plugins/wp-ga-count-master/wp-ga-count.php on line 285

Sometimes it can be fixed by refreshing the page, but most of the time can't.

The Snapshot would look like this
![wp-ga-bug](https://user-images.githubusercontent.com/30277172/28346871-512a125c-6c66-11e7-8d9a-fde53cc83962.jpg)

Is this just a conflict to my theme? Can you help for this? 

Thank you.

**Comment by mark2me** [comment]
I fixed the bug. You can download 'wp-ga-count.php' again and replace old file. 
Good luck!

**Comment by lf2eddie** [comment]
It worked. Thanks a lot.
